### ISSUE TITLE
What the fuck is this powergame shit right there?

### ISSUE THREAD

**Issue by WhiteFox08** [HippieStationArchive/HippieStation13-2#25]
![zdyqy3](https://cloud.githubusercontent.com/assets/2702850/22632975/3fc45a58-ebe3-11e6-855a-d4ef9edc5db3.png)
what the fuck

**Comment by tortellinitony** [comment]
why are they unpowered

**Comment by j-mie** [comment]
I think he took it on the live server, rather then debug server

**Comment by KittyKathy** [comment]
That's the Russian room it has intercoms to spy on every department, a security console monitor, a crew monitor and enough food to last the round. No one really uses it though and if they do it's to use the crew monitor/cams to find people as you only need maintenance access to get to this room.

**Comment by WhiteFox08** [comment]
@KittyKathy this is utterly pointless as its going to be first thing people are going to break into with no effort.

**Comment by tortellinitony** [comment]
this was already on hippie

**Comment by Sarcalogo** [comment]
whitefox btfo

**Comment by KittyKathy** [comment]
It's pretty much open to anyone with maintenance access and I don't see any glorious loot? this was on hippie already before any of the rebases it was never a a issue. I don't see how this is "powergaming shit" more of a gimmicky easter egg to me. You know the Russians are spying on us thing. The first thing people are going to break into is always the armory because it's protected by glass windows/windoors like seriously? the tide is strong in this map.

**Comment by ghost** [comment]
>Spying on comms is too OP.

You could already do this via the tcomms communications console logs.

**Comment by JohnGinnane** [comment]
This was on old hippie, unless there's something we're missing?

**Comment by Spacedong** [comment]
whitefox btfo

**Comment by Pyko1** [comment]
I really need to add a modular computer there for extra spying.
