### ISSUE TITLE
Cloning/ brain damage bug

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-2#345]
In-Game report from machinimal:
Revision info: Server revision 288eca3d7d0346521d83a97a033471c60f72f17a compiled on: 2017-02-23

>General description of the issue
You get brain damage from cloning, so when the game automatically makes you say stuff you die, because it's whisper while you're in crit (i think this is why, seem to die in cryo before it finishes)

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by cacogen** [comment]
oh, so this is what is causing all those [Medical] cloning pod states, "The cloning of x has been aborted due to unrecoverable tissue failure." messages

**Comment by KittyKathy** [comment]
Oh so this was caused by the nearcrit port #334 It seems that it does not work as it did pre rebase when you whisper something in crit now it treats it as your dying words and kills you. It used to be that you could whisper whatever you wanted while in crit until you hit deep crit and went unconscious then it would be your final words.

**Comment by JohnGinnane** [comment]
Fixes in https://github.com/HippieStation/HippieStation13/pull/378
