### ISSUE TITLE
can't send radio messages while whispering

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-2#410]
In-Game report from cacogen:
Revision info: Server revision 58f1e1d07922a9c8ca18d6b7142aebee061c3f22 compiled on: 2017-03-04

Landon Leslie whispers, ";HELP IN HYDROPONICS BACKROOM"

**Comment by JohnGinnane** [comment]
Were you crit?

**Comment by cacogen** [comment]
yeah but it doesn't work even when you aren't

maybe you want to stop people using the radio in crit, but i think it'd be a cool feature if you could use the radio while whispering. seems like an oversight that it includes the semicolon anyway

**Comment by cacogen** [comment]
whispering seems kind of fucked in general tbh

`Butch Harrold whispers, "I DON&#39;T-T-T-T W-W-W-WAN-N-N-NT T-T-T-TO SET-T T-TH-HE W-W-WOOOOOOOOOOOOR-RLD-D ON-N F-F-FIIIIIIIIIIIIIIIIIIIIIR-RE"`

the html character reference instead of an apostrophe is what i mean

**Comment by Sarcalogo** [comment]
You're not supposed to be able to, get good.

**Comment by cacogen** [comment]
it seems like a bug to do with symbols not parsing properly in whispers
bugs are always intended when they support your playstyle

anyway this should probably be closed because when you use the radio people can't hear you unless you're on the same tile as them anyway and it's probably a bad idea to let people use the radio in crit

**Comment by Pyko1** [comment]
I recall there was an issue about some html shit and whisper being italics.
Too bad the old issues seem to have been vanished on old git.

But i think this is the fix that we used last time to fix shit about italics.
https://github.com/HippieStationCode/HippieStation13/pull/2873

**Comment by cacogen** [comment]
station names also need the proper parsing. i've noticed that symbol bug a lot but that's the only other one i remember

**Comment by cacogen** [comment]
so it's actually just a bug with symbols while whispering in nearcrit. it has nothing to do with the radio.  normal whispers work as intended.

the problem has something to do with this:
https://github.com/HippieStation/HippieStation13/blob/master/code/modules/mob/living/say.dm#L86

**Comment by cacogen** [comment]
so the problem was html_encode being run on the message twice while using say in nearcrit. the say proc runs sanitise() on it, which calls html_encode(), then the whisper proc calls html_encode() on it again. this makes the symbols display as character references for some reason.

the problem with the station charter is stripped_input() fucking up symbols. this happens all over the place. book titles and chem master bottles are two other examples. not sure how to fix that.
