### ISSUE TITLE
the "build your own shuttle" leaves you behind if you're unbuckled

### ISSUE THREAD

**Issue by cacogen** [HippieStationArchive/HippieStation13-2#67]
i was scrambling to find a seat, didn't get one in time, so it disappeared and left me in space outside of escape. i was definitely on a floor tile, and none of the tiles failed to be picked up.

also this probably only a cosmetic issue but the tiles are picked up in sections when the shuttle leaves instead of all at once like with pre-built shuttles

**Comment by Ugons** [comment]
This seems to cause the same thing to the mining shuttle too if you bought the build-the-shuttle.

**Comment by KittyKathy** [comment]
Musical chairs hippie station style...if you don't get a seat before it leaves you phase through the shuttle and get left behind.
This is hilarious but a bug should probably fix it. I wonder if you could bring your own chair if this happened again to bypass this bug.

**Comment by yobob591** [comment]
gonna have to test dis

**Comment by KittyKathy** [comment]
Yeah I have witnessed this now, It moves the shuttle in sections which is weird because I think it's possible if the server lags and you end up near the edge of a section that got teleported the atmos might suck you out if you are not buckled and you get left behind in space. It's really weird and needs work it should move the shuttle all at once.

**Comment by yobob591** [comment]
this is actually all shuttles not just build your own, its just worse for build your own, id close this as we have an issue for it already

**Comment by cacogen** [comment]
#123
