### ISSUE TITLE
Remove true darkness

### ISSUE THREAD

**Issue by j-mie** [HippieStationArchive/HippieStation13-2#99]
We removed true darkness and just had it at like 90% alpha I think, check old icon

**Comment by GuyonBroadway** [comment]
There was a bug report on old Hippie that darkness did nothing so the effects of darkness were up for debate.

Personally I prefer true darkness as it provides opportunities for the robust to hide in ambush. It's also really cool now that E-swords stand out in the dark and give off light.

**Comment by JohnGinnane** [comment]
I agree, true darkness makes maint much more dangerous and allows for ambushing

**Comment by MethMedic** [comment]
Yea true darkness is really cool

**Comment by ghost** [comment]
True darkness is better.
Speaking of which, ghosts need to have darkness disabled by default. Fuck toggling it on every time.

**Comment by ghost** [comment]
thing is, true darkness tended to be true if, im not sure if it was just one or the other, you wore any type of sunglasses or general eyewear. 

and I think it worked well that way, since you sacrifice your ability to see in darkness but make yourself more vunerable in case you didn't bring enough flashlights and flares to become a sun, whilst having slightly more protection against certain stuns, whilst without eyewear you were able to see a bit better in the darkness but were more prone to flashes etc.

**Comment by ghost** [comment]
Any glasses removed it IIRC? but yeah, it was an interesting mechanic but ultimately it was too valuable to be able to see in the dark. I prefer true darkness since it makes thermals and other stealth stuff in maint far better.

**Comment by Spacedong** [comment]
true darkness is really good

**Comment by j-mie** [comment]
Cool - we'll keep it.
